language: go

install:
  - go get -t -v golang.org/x/tools/cmd/cover
  - go get -t -v -u github.com/golang/lint/golint

go:
  - 1.3
  - 1.4
  - 1.5
  
after_success:
  - cd $HOME/gopath/src/github.com/gotterdemarung/go-noncense
  - gofmt -e -l ./
  - golint ./... | grep -v 'comment'
